// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC24N5JdlOOrigoxrh1N4UVepoaYmHNOPM',
    appId: '1:730546548700:web:78c3de377514c3ee0b6919',
    messagingSenderId: '730546548700',
    projectId: 'recipeapp-e6f37',
    authDomain: 'recipeapp-e6f37.firebaseapp.com',
    storageBucket: 'recipeapp-e6f37.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHOAe4fiLPHvHnYJwoPik2UwiOU33IPgI',
    appId: '1:730546548700:android:446d7b33bf7f04e20b6919',
    messagingSenderId: '730546548700',
    projectId: 'recipeapp-e6f37',
    storageBucket: 'recipeapp-e6f37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd0KBuMxaCAwikyQO3dz7sf0ICSq27QDI',
    appId: '1:730546548700:ios:e9b0f70dd96bed910b6919',
    messagingSenderId: '730546548700',
    projectId: 'recipeapp-e6f37',
    storageBucket: 'recipeapp-e6f37.firebasestorage.app',
    iosBundleId: 'com.karthik.recipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd0KBuMxaCAwikyQO3dz7sf0ICSq27QDI',
    appId: '1:730546548700:ios:a87a00c384258afb0b6919',
    messagingSenderId: '730546548700',
    projectId: 'recipeapp-e6f37',
    storageBucket: 'recipeapp-e6f37.firebasestorage.app',
    iosBundleId: 'com.example.recipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC24N5JdlOOrigoxrh1N4UVepoaYmHNOPM',
    appId: '1:730546548700:web:b305275ad94cc5420b6919',
    messagingSenderId: '730546548700',
    projectId: 'recipeapp-e6f37',
    authDomain: 'recipeapp-e6f37.firebaseapp.com',
    storageBucket: 'recipeapp-e6f37.firebasestorage.app',
  );

}